scala_library(
    dependencies=[
                  '3rdparty/jvm/org/elasticsearch:rest6',
                  '3rdparty/jvm/org/elasticsearch:sniffer6',
                 ],
    sources=rglobs('*.scala'),
)
